# Generated by Django 3.0.7 on 2020-06-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_messagebird', '0003_messagebirdvoicedevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebirdvoicedevice',
            name='language',
            field=models.CharField(default='en-us', help_text='The language in which the message needs to be read to the recipient. Possible values can be found here: https://developers.messagebird.com/api/voice-messaging/#the-voice-message-object', max_length=5),
        ),
    ]
